-- Assuming you have a table named 'Feedback' with the appropriate columns

INSERT INTO Admin_Feedback (FeedBackId, AdminId, FeedBack, Rating, PhoneNumber, TransactionFee, SupportPolicy, LegalStatus)
VALUES
(1, 14, 'Effective management and great customer service, highly recommended.', 1.6, '561-865-8746', 39, 'We are dedicated to providing excellent customer service and resolving your inquiries efficiently.', 0),
(2, 16, 'Needs improvement in responsiveness and problem-solving skills.', 0.1, '650-137-6719', 79, 'Our commitment is to address your concerns promptly and find effective solutions.', 1),
(3, 21, 'Good effort but lacks in strategic planning and execution.', 0.4, '607-324-6246', 39, 'We are refining our strategies to improve execution and service delivery.', 1),
(4, 27, 'Strong in operational management, could be more innovative.', 0.5, '841-782-0391', 92, 'We excel in operations and are exploring innovative approaches to enhance our services.', 1),
(5, 21, 'Average performance, needs to focus more on customer engagement.', 2.2, '371-706-5182', 76, 'We are actively working on enhancing customer engagement in our services.', 1),
(6, 38, 'Excellent in crisis management, very reliable and efficient.', 1.5, '937-310-6442', 56, 'You can count on us for reliable and efficient crisis management services.', 0),
(7, 4, 'Consistently performs well, great team management skills.', 0.2, '885-588-3908', 37, 'We maintain consistent performance and excel in team management.', 1),
(8, 2, 'Struggles with timely decision-making, needs improvement.', 4.7, '451-907-4465', 93, 'We are actively improving our decision-making process for timeliness and efficiency.', 1),
(9, 34, 'Good team collaboration but slow in decision-making.', 3.1, '456-873-2348', 49, 'We prioritize teamwork while enhancing decision-making efficiency.', 1),
(10, 39, 'Effective communication and client relations, highly efficient.', 1.7, '822-422-4096', 33, 'Our strength lies in communication and maintaining high efficiency in client relations.', 1),
(11, 36, 'Shows potential in customer service, but needs more experience.', 4.8, '759-746-5169', 7, 'We acknowledge potential in customer service and are committed to gaining more experience.', 1),
(12, 26, 'Strong in administrative tasks, but lacks creative approach.', 4.9, '792-473-5926', 16, 'We excel in administrative tasks and are working on introducing a more creative approach.', 1),
(13, 26, 'Capable in handling tasks, needs to improve efficiency.', 2.9, '733-130-4327', 26, 'We aim to improve efficiency while maintaining our capability in handling tasks.', 0),
(14, 14, 'Effective in customer relations, could improve in strategic areas.', 3.6, '968-508-6850', 83, 'We focus on effective customer relations and are working to enhance our strategic capabilities.', 0),
(15, 7, 'Great leadership skills, but needs to be more proactive.', 3.0, '690-163-0022', 65, 'We recognize our leadership skills and strive to be more proactive in our approach.', 0),
(16, 16, 'Good operational skills, needs to improve in customer engagement.', 3.3, '764-762-7877', 75, 'Our strength lies in operational skills, and we are enhancing customer engagement efforts.', 0),
(17, 16, 'Efficient in task management, but lacks innovation.', 1.3, '751-950-2024', 100, 'We efficiently manage tasks and are actively exploring innovative approaches.', 0),
(18, 28, 'Highly skilled in financial management, very reliable.', 4.8, '542-226-1164', 17, 'We are highly skilled in financial management and prioritize reliability.', 1),
(19, 23, 'Needs to develop better strategies for team management.', 1.1, '724-224-3144', 68, 'We are actively developing better team management strategies.', 1),
(20, 10, 'Adaptable and proactive in handling challenges.', 3.0, '740-509-7555', 3, 'Our adaptability and proactive approach are key strengths in handling challenges.', 1),
(21, 2, 'Shows promise in leadership but needs more experience.', 4.8, '759-746-5169', 7, 'We acknowledge leadership potential and are dedicated to gaining more experience.', 1),
(22, 14, 'Strong in customer engagement and efficient operations.', 4.9, '792-473-5926', 16, 'We excel in customer engagement and ensure efficient operations.', 1),
(23, 23, 'Effective communicator but needs improvement in strategy.', 2.9, '733-130-4327', 26, 'We prioritize effective communication and are working on refining our strategic approach.', 0),
(24, 31, 'Highly responsive and dedicated to customer satisfaction.', 3.6, '968-508-6850', 83, 'We are highly responsive and dedicated to ensuring your satisfaction.', 0),
(25, 9, 'Needs more focus on efficient workflow and management.', 3.0, '690-163-0022', 65, 'We are actively focusing on improving workflow efficiency and effective management.', 0),
(26, 37, 'Shows potential in customer service, but lacks consistency.', 3.3, '764-762-7877', 75, 'We recognize potential in customer service and are working on maintaining consistency.', 0),
(27, 3, 'Efficient in handling complex tasks and problems.', 1.3, '751-950-2024', 100, 'We efficiently handle complex tasks and actively seek innovative solutions.', 0),
(28, 26, 'Good at operational tasks, needs to improve in strategy.', 4.8, '542-226-1164', 17, 'We excel in operational tasks and are enhancing our strategic capabilities.', 1),
(29, 5, 'Competent in regular duties, innovative approach needed.', 1.1, '724-224-3144', 68, 'We are competent in regular duties and actively exploring innovative approaches.', 1),
(30, 31, 'Excellent in strategic planning and team management.', 3.0, '740-509-7555', 3, 'Our strength lies in strategic planning and effective team management.', 1),
(31, 24, 'Strong leadership skills, effective in decision making.', 4.8, '759-746-5169', 7, 'We recognize our strong leadership skills and effective decision-making capabilities.', 1),
(32, 32, 'Adequate performance, but can improve in customer relations.', 4.9, '792-473-5926', 16, 'We aim to maintain adequate performance while improving customer relations.', 1),
(33, 2, 'Needs to develop better communication and team skills.', 2.9, '733-130-4327', 26, 'We are actively developing better communication and team-building skills.', 0),
(34, 19, 'Efficient in task management, needs to focus on innovation.', 3.6, '968-508-6850', 83, 'Efficiency in task management remains our priority while exploring innovative solutions.', 0),
(35, 15, 'Good at handling routine tasks, needs to improve in crisis management.', 3.0, '690-163-0022', 65, 'We handle routine tasks well and are working on enhancing crisis management capabilities.', 0),
(36, 35, 'Shows potential in strategic planning, but lacks execution.', 3.3, '764-762-7877', 75, 'We see potential in strategic planning and are focused on improving execution.', 0),
(37, 14, 'Effective in team leadership, great at problem-solving.', 1.3, '751-950-2024', 100, 'We are effective in team leadership and excel in problem-solving.', 0),
(38, 13, 'Capable and efficient, but needs to work on innovation.', 4.8, '542-226-1164', 17, 'We are capable and efficient, continuously striving to innovate.', 1),
(39, 1, 'Strong in customer service and operational efficiency.', 1.1, '724-224-3144', 68, 'We excel in customer service and operational efficiency.', 1),
(40, 31, 'Highly skilled in customer relations and management.', 3.0, '740-509-7555', 3, 'We possess high skills in customer relations and effective management.', 1);
