-- CREATE TABLE Cus_res (
--     customerID INT,
--     restaurantID INT,
--     OrderDetail VARCHAR(1000),
--     FOREIGN KEY (customerID) REFERENCES Customer(customerID) ON UPDATE CASCADE ON DELETE CASCADE,
--     FOREIGN KEY (restaurantID) REFERENCES Restaurant(restaurantID) ON UPDATE CASCADE ON DELETE CASCADE
-- );


INSERT INTO Cus_res (customerID, restaurantID, OrderDetail)
VALUES
    (20, 11, 'Please prepare a vegetarian pasta with extra cheese and garlic bread for takeaway.'),
    (5, 4, 'I would like a medium-rare steak with mashed potatoes and a side salad for dine-in.'),
    (21, 6, 'Deliver a family-sized pizza with pepperoni, mushrooms, and extra cheese as soon as possible.'),
    (38, 5, 'Prepare a seafood platter with lobster, shrimp, and crab for a special celebration.'),
    (24, 3, 'I need a gluten-free, vegan-friendly sandwich with plenty of veggies for lunch.'),
    (14, 21, 'Please bring a bottle of your finest red wine and a cheese platter to table 6.'),
    (19, 26, 'Deliver a dessert sampler with a variety of cakes and pastries to our office.'),
    (33, 24, 'We have a group of 10. We need a reservation and a customized menu for a birthday dinner.'),
    (1, 14, 'Prepare a three-course meal for a romantic dinner tonight, including a vegetarian option.'),
    (40, 31, 'Catering needed for a corporate event next week. Please provide menu options and pricing.'),
    (2, 22, 'Can you deliver sushi rolls with a mix of sashimi for our sushi night at home?'),
    (7, 12, 'I have a food allergy; please ensure no nuts are used in my order.'),
    (32, 40, 'We need a buffet-style lunch with vegetarian and non-vegetarian options for 50 people.'),
    (36, 28, 'Please arrange a tasting menu for our anniversary dinner next Saturday.'),
    (11, 9, 'We need a large order of sandwiches and salads for a corporate lunch meeting.'),
    (22, 25, 'Deliver a platter of assorted appetizers for our office party this evening.'),
    (30, 34, 'We are celebrating a milestone. Can you create a customized cake for the occasion?'),
    (23, 39, 'We need a delivery of fresh fruit baskets for our office's health and wellness program.'),
    (6, 35, 'Please prepare a hearty breakfast for our group of 15 with a mix of omelets and pancakes.'),
    (25, 7, 'We are looking for a wine pairing recommendation for our anniversary dinner.'),
    (13, 29, 'Can you cater a buffet-style lunch for our workshop with options for vegetarian and gluten-free diets?'),
    (35, 17, 'We need a reservation for 6 and would like the chef to surprise us with their specialties.'),
    (8, 19, 'Deliver a box of assorted pastries and coffee for our morning meeting.'),
    (9, 38, 'Please prepare a special anniversary cake with a romantic design and personalized message.'),
    (39, 10, 'We have a family gathering. We need a buffet with diverse dishes and kid-friendly options.'),
    (4, 13, 'Please create a chef's tasting menu with wine pairings for our anniversary celebration.'),
    (18, 27, 'We need a banquet-style dinner for our company's year-end party.'),
    (10, 16, 'Can you prepare a surprise birthday cake for our colleague?'),
    (12, 18, 'We are a group of 8. We need a reservation and would like to pre-order dishes.'),
    (3, 33, 'We have a team meeting. Provide lunch with both vegetarian and non-vegetarian options.'),
    (31, 15, 'We need a reservation for 2 at a cozy table for our date night.'),
    (15, 32, 'Please prepare a special dessert for my partner's birthday.'),
    (34, 30, 'Catering needed for a company training event. We require a buffet with dietary options.'),
    (26, 37, 'Deliver a variety of sandwiches and wraps for our office lunch meeting.'),
    (16, 2, 'We are hosting a cocktail party. Please provide appetizers and finger foods.'),
    (28, 8, 'Catering needed for our business conference. We require a buffet for 100 attendees.'),
    (17, 36, 'We need a reservation for 4 people and would like to be seated by the window.'),
    (29, 20, 'Deliver a mix of pasta dishes for our team's working lunch meeting.'),
    (37, 23, 'Can you arrange a special birthday cake with a surprise inside for our celebration?'),
    (27, 1, 'We are looking for a wine recommendation to pair with our dinner tonight.'),
    (5, 27, 'Prepare a seafood platter with oysters, crab, and shrimp for a special occasion.'),
    (3, 13, 'We have a team lunch. Please ensure there are vegetarian and gluten-free options.'),
    (38, 37, 'We need a reservation for 10 guests and would like a private dining area.'),
    (9, 30, 'Deliver a variety of sandwiches and salads for our office lunch meeting.'),
    (2, 5, 'We need a delivery of sushi rolls for a sushi night at our friend's place.'),
    (14, 25, 'Please arrange a wine and cheese tasting experience for our group of 6.'),
    (16, 12, 'We are celebrating our anniversary. Please create a custom menu for our dinner.'),
    (18, 22, 'Deliver a box of assorted desserts for our team's celebration.'),
    (29, 40, 'We have a company event. Can you provide catering with a mix of appetizers and entrees?'),
    (25, 35, 'We need a reservation for 2 and would like a quiet corner table by the window.'),
    (8, 9, 'Deliver a selection of sandwiches and wraps for our office lunch meeting.'),
    (30, 1, 'We have a corporate event. Please provide a buffet with vegetarian and non-vegetarian options.'),
    (17, 32, 'Please prepare a special dessert for our group of 5 celebrating a milestone.'),
    (1, 21, 'Deliver a bottle of champagne and a seafood platter for our anniversary celebration.'),
    (40, 38, 'We are hosting a party. Can you arrange a buffet with diverse dishes and snacks?'),
    (31, 39, 'We need catering for a team-building event. Provide a buffet with various options.'),
    (37, 16, 'Deliver a box of assorted pastries and coffee for our morning meeting.'),
    (34, 31, 'We have a group dinner. Please prepare a customized menu for our celebration.'),
    (22, 36, 'We need a reservation for 8 and would like a table in a quieter section of the restaurant.'),
    (20, 26, 'Prepare a family-sized pasta dish with a mix of vegetables and a garlic bread for delivery.'),
    (11, 18, 'We are hosting a business lunch. Can you provide a buffet with a variety of options?'),
    (7, 28, 'Please prepare a surprise dessert for our special occasion tonight.'),
    (39, 6, 'Deliver a selection of appetizers and finger foods for our office happy hour.'),
    (13, 3, 'We have a team lunch. Please provide sandwiches and salads for our group.'),
    (35, 14, 'Please arrange a wine pairing experience for our group of 4 during dinner.'),
    (4, 17, 'Deliver a chef's tasting menu with wine pairings for our anniversary celebration.'),
    (10, 19, 'We need a reservation for 6 and would like a table with a nice view.'),
    (36, 23, 'Please prepare a special dessert for our party of 10.'),
    (24, 34, 'Catering needed for our company's annual dinner. Provide a buffet with a variety of dishes.'),
    (23, 29, 'Deliver a platter of fresh fruit for our office's health and wellness program.'),
    (12, 15, 'We are celebrating a birthday. Please arrange a surprise cake for our party of 8.'),
    (15, 4, 'Prepare a three-course meal for a special occasion, including vegetarian options.'),
    (27, 8, 'We have a team dinner. Please recommend a wine that pairs well with our chosen dishes.'),
    (33, 24, 'Deliver a variety of appetizers for our cocktail party.'),
    (6, 10, 'Please prepare a buffet-style breakfast for our group of 15.'),
    (19, 20, 'We need catering for a corporate event. Provide a buffet with diverse dishes and desserts.'),
    (28, 33, 'Catering needed for our company meeting. Provide lunch with various options.'),
    (32, 11, 'Deliver a mix of sandwiches and wraps for our team's working lunch meeting.'),
    (26, 37, 'We have an office lunch meeting. Please provide a variety of sandwiches and salads.'),
    (21, 2, 'Prepare a sushi platter with a mix of rolls for our sushi night at home.');
