-- Assuming you have a table named 'FoodItems' with the appropriate columns

INSERT INTO FoodItem_Ava_P (FoodId, FoodName, Availability, Price)
VALUES
(1, 'Spaghetti Carbonara', true, 8),
(2, 'Margherita Pizza', false, 65),
(3, 'Chicken Alfredo', true, 46),
(4, 'Filet Mignon Steak', true, 90),
(5, 'Salmon Teriyaki', true, 73),
(6, 'Caesar Salad', false, 89),
(7, 'Sushi Platter', false, 18),
(8, 'Vegetable Stir-Fry', false, 62),
(9, 'Shrimp Scampi', false, 75),
(10, 'Beef Tacos', false, 44),
(11, 'Grilled Salmon', false, 27),
(12, 'Mushroom Risotto', false, 34),
(13, 'Chicken Parmesan', false, 46),
(14, 'Caprese Salad', false, 23),
(15, 'Lobster Bisque', false, 92),
(16, 'BBQ Ribs', false, 43),
(17, 'Vegetable Lasagna', false, 71),
(18, 'Margherita Pizza', true, 11),
(19, 'Crispy Chicken Wings', false, 28),
(20, 'Sushi Rolls', false, 46),
(21, 'Beef Stir-Fry', false, 69),
(22, 'Penne Alfredo', false, 36),
(23, 'Chicken Noodle Soup', false, 5),
(24, 'Vegetable Fajitas', false, 37),
(25, 'Teriyaki Chicken Bowl', false, 48),
(26, 'Pesto Pasta', false, 31),
(27, 'Grilled Ribeye Steak', true, 82),
(28, 'Margherita Pizza', true, 21),
(29, 'Baked Ziti', false, 47),
(30, 'Chicken Caesar Salad', true, 10),
(31, 'Cheeseburger', true, 2),
(32, 'Shrimp Scampi', false, 51),
(33, 'New York Strip Steak', true, 96),
(34, 'Vegetable Sushi Rolls', false, 45),
(35, 'Clam Chowder', false, 6),
(36, 'Grilled Chicken Sandwich', true, 56),
(37, 'Bacon Wrapped Scallops', false, 97),
(38, 'Beef and Broccoli', true, 94),
(39, 'Vegetable Pad Thai', false, 63),
(40, 'Seafood Paella', false, 65);
